# Port for the Frontend/BFF
server.port=8080

# The URL of your Backend (Computer B)
# Note: Use the actual IP if they are on different machines
backend.api.url=http://10.30.74.84:8081/api

# Thymeleaf Settings
# Defaults are used (classpath:/templates/ and .html)
spring.thymeleaf.cache=false

# Security / Session Settings
# This keeps the user logged in on the Frontend
spring.session.timeout=30m

# Logging (Useful for debugging HttpClient calls)
logging.level.org.example.frontend=DEBUG

# Test User
spring.security.user.name=john@test.com
spring.security.user.password=password